-- Criação das sequências
CREATE SEQUENCE seq_cliente START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_passagem START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_reserva START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE seq_pagamento START WITH 1 INCREMENT BY 1;

-- Tabela Clientes e trigger
CREATE TABLE Hospedes (
    id_cliente INT PRIMARY KEY, 
    nome VARCHAR2(150) NOT NULL, 
    email VARCHAR2(150) UNIQUE NOT NULL, 
    telefone VARCHAR2(20),
    CPF VARCHAR2(11)
);
CREATE OR REPLACE TRIGGER trg_hospede_id
BEFORE INSERT ON Hospedes FOR EACH ROW
BEGIN
    SELECT seq_cliente.NEXTVAL INTO :NEW.id_cliente FROM dual;
END;